#!/bin/sh
#EXPORT_DIR="/opt/lf2/liquid_feedback_frontend/download"
EXPORT_DIR="/opt/exports"

if [ -z "$1" ]; then
  echo "Usage: $0 <database>"
  echo " => Export '<database>' to '$EXPORT_DIR/<database>/<database>_<date>.sql.gz'"
  exit 1
fi

DATABASE="$1"
EXPORT_DBNAME="$1_autoexport"
EXPORT_FILE="$EXPORT_DIR/$1/$1_$(date +"%Y-%m-%d_%H-%M-%Z").sql.gz"
retval=0

echo "Dropping database \"$EXPORT_DBNAME\" if existent..."
dropdb "$EXPORT_DBNAME" 2> /dev/null
echo "Copying database \"$DATABASE\" to new database \"$EXPORT_DBNAME\"..."
# TODO: use character encoding of original database
if (createdb "$EXPORT_DBNAME" && pg_dump "$DATABASE" | psql -f - "$EXPORT_DBNAME" > /dev/null)
then
  echo "Deleting private data in copied database..."
  if psql -v ON_ERROR_STOP=1 -c 'SELECT delete_private_data()' "$EXPORT_DBNAME" > /dev/null
  then
    echo "Dumping and compressing copied database to \"$EXPORT_FILE\"..."
    if pg_dump --no-owner --no-privileges "$EXPORT_DBNAME" | gzip -9 > "$EXPORT_FILE"
    then
      true
    else
      retval=4
    fi
  else
    retval=3
  fi
else
  retval=2
fi
echo "Dropping database \"$EXPORT_DBNAME\"..."
dropdb "$EXPORT_DBNAME"
echo "DONE."
exit $retval
